export * from './administration.service';
import { AdministrationService } from './administration.service';
export * from './authentification.service';
import { AuthentificationService } from './authentification.service';
export * from './badges.service';
import { BadgesService } from './badges.service';
export * from './challenges.service';
import { ChallengesService } from './challenges.service';
export * from './classes.service';
import { ClassesService } from './classes.service';
export * from './dfis.service';
import { DfisService } from './dfis.service';
export * from './exercices.service';
import { ExercicesService } from './exercices.service';
export * from './livres.service';
import { LivresService } from './livres.service';
export * from './lve.service';
import { LveService } from './lve.service';
export * from './matires.service';
import { MatiresService } from './matires.service';
export * from './niveaux.service';
import { NiveauxService } from './niveaux.service';
export const APIS = [AdministrationService, AuthentificationService, BadgesService, ChallengesService, ClassesService, DfisService, ExercicesService, LivresService, LveService, MatiresService, NiveauxService];
