export * from './administration.service';
import { AdministrationService } from './administration.service';
export * from './authentification.service';
import { AuthentificationService } from './authentification.service';
export * from './badges.service';
import { BadgesService } from './badges.service';
export * from './challenges.service';
import { ChallengesService } from './challenges.service';
export * from './conversions.service';
import { ConversionsService } from './conversions.service';
export * from './dfis.service';
import { DfisService } from './dfis.service';
export * from './exercices.service';
import { ExercicesService } from './exercices.service';
export * from './iADucative.service';
import { IADucativeService } from './iADucative.service';
export * from './livres.service';
import { LivresService } from './livres.service';
export * from './livresFichiers.service';
import { LivresFichiersService } from './livresFichiers.service';
export * from './lve.service';
import { LveService } from './lve.service';
export * from './partenaires.service';
import { PartenairesService } from './partenaires.service';
export * from './quizzes.service';
import { QuizzesService } from './quizzes.service';
export * from './statistiques.service';
import { StatistiquesService } from './statistiques.service';
export const APIS = [AdministrationService, AuthentificationService, BadgesService, ChallengesService, ConversionsService, DfisService, ExercicesService, IADucativeService, LivresService, LivresFichiersService, LveService, PartenairesService, QuizzesService, StatistiquesService];
