/**
 * API EDUGO - Plateforme Éducative Malienne
 *
 * Contact: support@edugo.ml
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Participation } from './participation';
import { Niveau } from './niveau';
import { Classe } from './classe';
import { Question } from './question';
import { Badge } from './badge';


export interface Challenge { 
    id?: number;
    titre?: string;
    description?: string;
    dateDebut?: string;
    dateFin?: string;
    rewardMode?: string;
    typeChallenge?: Challenge.TypeChallengeEnum;
    niveau?: Niveau;
    classe?: Classe;
    rewards?: Array<Badge>;
    questionsChallenge?: Array<Question>;
    participations?: Array<Participation>;
}
export namespace Challenge {
    export const TypeChallengeEnum = {
        Interclasse: 'INTERCLASSE',
        Interniveau: 'INTERNIVEAU'
    } as const;
    export type TypeChallengeEnum = typeof TypeChallengeEnum[keyof typeof TypeChallengeEnum];
}


