/**
 * API EDUGO - Plateforme Éducative Malienne
 *
 * Contact: support@edugo.ml
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Niveau } from './niveau';
import { Classe } from './classe';


export interface Challenge { 
    id?: number;
    titre?: string;
    description?: string;
    dateDebut?: string;
    dateFin?: string;
    points?: number;
    rewardMode?: string;
    typeChallenge?: Challenge.TypeChallengeEnum;
    niveau?: Niveau;
    classe?: Classe;
}
export namespace Challenge {
    export const TypeChallengeEnum = {
        Interclasse: 'INTERCLASSE',
        Interniveau: 'INTERNIVEAU'
    } as const;
    export type TypeChallengeEnum = typeof TypeChallengeEnum[keyof typeof TypeChallengeEnum];
}


