/**
 * API EDUGO - Plateforme Éducative Malienne
 *
 * Contact: support@edugo.ml
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ChatRequest { 
    sessionId?: number;
    eleveId?: number;
    livreId?: number;
    matiereId?: number;
    message?: string;
}

