/**
 * API EDUGO - Plateforme Éducative Malienne
 *
 * Contact: support@edugo.ml
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Eleve } from './eleve';
import { OptionsConversion } from './optionsConversion';


export interface ConversionEleve { 
    id?: number;
    option?: OptionsConversion;
    eleve?: Eleve;
    dateConversion?: string;
}

