/**
 * API EDUGO - Plateforme Éducative Malienne
 *
 * Contact: support@edugo.ml
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Classe } from './classe';


export interface QuestionDefi {
  id?: number;
  texte: string;
  type?: string;
  points?: number;
  bonneReponse?: string;
  reponses?: ReponseDefi[];
}

export interface ReponseDefi {
  id?: number;
  texte: string;
  estCorrecte: boolean;
}

export interface Defi { 
    id?: number;
    titre?: string;
    ennonce?: string;
    dateAjout?: string;
    reponseDefi?: string;
    pointDefi?: number;
    nbreParticipations?: number;
    typeDefi?: string;
    classe?: Classe;
    questions?: QuestionDefi[];
}

