/**
 * API EDUGO - Plateforme Éducative Malienne
 *
 * Contact: support@edugo.ml
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { EleveDefi } from './eleveDefi';
import { Classe } from './classe';


export interface Defi { 
    id?: number;
    titre?: string;
    ennonce?: string;
    dateAjout?: string;
    reponseDefi?: string;
    pointDefi?: number;
    nbreParticipations?: number;
    typeDefi?: string;
    classe?: Classe;
    eleveDefis?: Array<EleveDefi>;
}

