/**
 * API EDUGO - Plateforme Éducative Malienne
 *
 * Contact: support@edugo.ml
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Eleve } from './eleve';
import { Defi } from './defi';


export interface EleveDefi { 
    id?: number;
    reponseUtilisateur?: string;
    dateEnvoie?: string;
    dateParticipation?: string;
    statut?: string;
    eleve?: Eleve;
    defi?: Defi;
}

