/**
 * API EDUGO - Plateforme Éducative Malienne
 *
 * Contact: support@edugo.ml
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { EleveDefi } from './eleveDefi';
import { Progression } from './progression';
import { ConversionEleve } from './conversionEleve';
import { Participation } from './participation';
import { Suggestion } from './suggestion';
import { GrantedAuthority } from './grantedAuthority';
import { Classe } from './classe';
import { FaireExercice } from './faireExercice';
import { ReponseEleve } from './reponseEleve';


export interface Eleve { 
    id?: number;
    nom?: string;
    prenom?: string;
    email?: string;
    motDePasse?: string;
    role?: Eleve.RoleEnum;
    dateCreation?: string;
    dateModification?: string;
    estActive?: boolean;
    photoProfil?: string;
    dateNaissance?: string;
    classe?: Classe;
    pointAccumule?: number;
    participations?: Array<Participation>;
    progressions?: Array<Progression>;
    eleveDefis?: Array<EleveDefi>;
    faireExercices?: Array<FaireExercice>;
    reponsesUtilisateurs?: Array<ReponseEleve>;
    conversions?: Array<ConversionEleve>;
    suggestions?: Array<Suggestion>;
    enabled?: boolean;
    password?: string;
    username?: string;
    authorities?: Array<GrantedAuthority>;
    accountNonExpired?: boolean;
    credentialsNonExpired?: boolean;
    accountNonLocked?: boolean;
}
export namespace Eleve {
    export const RoleEnum = {
        Admin: 'ADMIN',
        Eleve: 'ELEVE'
    } as const;
    export type RoleEnum = typeof RoleEnum[keyof typeof RoleEnum];
}


