/**
 * API EDUGO - Plateforme Éducative Malienne
 *
 * Contact: support@edugo.ml
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Matiere } from './matiere';
import { Niveau } from './niveau';
import { Question } from './question';
import { Livre } from './livre';


export interface Exercice { 
    id?: number;
    titre?: string;
    description?: string;
    niveauDifficulte?: number;
    tempsAlloue?: number;
    active?: boolean;
    dateCreation?: string;
    dateModification?: string;
    matiere?: Matiere;
    niveauScolaire?: Niveau;
    livre?: Livre;
    questionsExercice?: Array<Question>;
}

