/**
 * API EDUGO - Plateforme Éducative Malienne
 *
 * Contact: support@edugo.ml
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ExerciceResponse { 
    id?: number;
    titre?: string;
    active?: boolean;
    niveauDifficulte?: number;
    tempsAlloue?: number;
    matiereId?: number;
    matiereNom?: string;
}

