/**
 * API EDUGO - Plateforme Éducative Malienne
 *
 * Contact: support@edugo.ml
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ExerciceRequest { 
    titre?: string;
    description?: string;
    niveauDifficulte?: number;
    tempsAlloue?: number;
    active?: boolean;
    matiereId?: number;
    niveauId?: number;
    livreId?: number;
}

