/**
 * API EDUGO - Plateforme Éducative Malienne
 *
 * Contact: support@edugo.ml
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface FaireExerciceResponse { 
    id?: number;
    eleveId?: number;
    eleveNom?: string;
    exerciceId?: number;
    exerciceTitre?: string;
    reponse?: string;
    note?: number;
    commentaire?: string;
    statut?: string;
    dateSoumission?: string;
    dateCorrection?: string;
}

