/**
 * API EDUGO - Plateforme Éducative Malienne
 *
 * Contact: support@edugo.ml
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Eleve } from './eleve';
import { Exercice } from './exercice';


export interface FaireExercice { 
    id?: number;
    eleve?: Eleve;
    exercice?: Exercice;
    pointExercice?: number;
    statut?: FaireExercice.StatutEnum;
    dateExercice?: string;
    reponse?: string;
    dateSoumission?: string;
    note?: number;
    commentaire?: string;
    dateCorrection?: string;
}
export namespace FaireExercice {
    export const StatutEnum = {
        PasDebute: 'PAS_DEBUTE',
        Encours: 'ENCOURS',
        Termine: 'TERMINE',
        Soumis: 'SOUMIS',
        Corrige: 'CORRIGE'
    } as const;
    export type StatutEnum = typeof StatutEnum[keyof typeof StatutEnum];
}


