/**
 * API EDUGO - Plateforme Éducative Malienne
 *
 * Contact: support@edugo.ml
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface FichierLivreDto { 
    id?: number;
    nom?: string;
    type?: string;
    taille?: number;
    format?: string;
    chemin?: string;
}

