/**
 * API EDUGO - Plateforme Éducative Malienne
 *
 * Contact: support@edugo.ml
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Livre } from './livre';


export interface FichierLivre { 
    id?: number;
    nom?: string;
    cheminFichier?: string;
    type?: FichierLivre.TypeEnum;
    taille?: number;
    format?: string;
    livre?: Livre;
    tailleFormattee?: string;
}
export namespace FichierLivre {
    export const TypeEnum = {
        Pdf: 'PDF',
        Epub: 'EPUB',
        Image: 'IMAGE',
        Video: 'VIDEO',
        Audio: 'AUDIO'
    } as const;
    export type TypeEnum = typeof TypeEnum[keyof typeof TypeEnum];
}


