/**
 * API EDUGO - Plateforme Éducative Malienne
 *
 * Contact: support@edugo.ml
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface LivreRequest { 
    titre?: string;
    isbn?: string;
    description?: string;
    anneePublication?: number;
    editeur?: string;
    auteur?: string;
    totalPages?: number;
    imageCouverture?: string;
    lectureAuto?: boolean;
    interactif?: boolean;
    niveauId?: number;
    classeId?: number;
    matiereId?: number;
    langueId?: number;
}

