/**
 * API EDUGO - Plateforme Éducative Malienne
 *
 * Contact: support@edugo.ml
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface LivreDetailResponse { 
    id?: number;
    titre?: string;
    isbn?: string;
    auteur?: string;
    imageCouverture?: string;
    totalPages?: number;
    lectureAuto?: boolean;
    interactif?: boolean;
    anneePublication?: number;
    editeur?: string;
    niveauId?: number;
    niveauNom?: string;
    classeId?: number;
    classeNom?: string;
    matiereId?: number;
    matiereNom?: string;
    langueId?: number;
    langueNom?: string;
    progression?: number;
    statistiques?: any | null;
}

