/**
 * API EDUGO - Plateforme Éducative Malienne
 *
 * Contact: support@edugo.ml
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { FichierLivre } from './fichierLivre';
import { Progression } from './progression';
import { Quiz } from './quiz';
import { Langue } from './langue';
import { Matiere } from './matiere';
import { Niveau } from './niveau';
import { Classe } from './classe';
import { Tag } from './tag';


export interface Livre { 
    id?: number;
    titre?: string;
    isbn?: string;
    description?: string;
    anneePublication?: number;
    editeur?: string;
    auteur?: string;
    totalPages?: number;
    imageCouverture?: string;
    lectureAuto?: boolean;
    interactif?: boolean;
    niveau?: Niveau;
    classe?: Classe;
    matiere?: Matiere;
    langue?: Langue;
    fichiers?: Array<FichierLivre>;
    quiz?: Quiz;
    progressions?: Array<Progression>;
    tags?: Array<Tag>;
}

