/**
 * API EDUGO - Plateforme Éducative Malienne
 *
 * Contact: support@edugo.ml
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Réponse de connexion contenant les tokens JWT et les informations utilisateur
 */
export interface LoginResponse { 
    /**
     * Token JWT d\'accès
     */
    token?: string;
    /**
     * Token JWT de rafraîchissement
     */
    refreshToken?: string;
    /**
     * Email de l\'utilisateur
     */
    email?: string;
    /**
     * Nom de famille
     */
    nom?: string;
    /**
     * Prénom
     */
    prenom?: string;
    /**
     * Rôle de l\'utilisateur
     */
    role?: LoginResponse.RoleEnum;
    /**
     * ID unique de l\'utilisateur
     */
    id?: number;
}
export namespace LoginResponse {
    export const RoleEnum = {
        Admin: 'ADMIN',
        Eleve: 'ELEVE'
    } as const;
    export type RoleEnum = typeof RoleEnum[keyof typeof RoleEnum];
}


