/**
 * API EDUGO - Plateforme Éducative Malienne
 *
 * Contact: support@edugo.ml
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Demande de connexion
 */
export interface LoginRequest { 
    /**
     * Email de l\'utilisateur
     */
    email: string;
    /**
     * Mot de passe
     */
    motDePasse: string;
}

