/**
 * API EDUGO - Plateforme Éducative Malienne
 *
 * Contact: support@edugo.ml
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Exercice } from './exercice';


export interface Matiere { 
    id?: number;
    nom?: string;
    exercice?: Array<Exercice>;
}

