/**
 * API EDUGO - Plateforme Éducative Malienne
 *
 * Contact: support@edugo.ml
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Classe } from './classe';
import { Livre } from './livre';
import { Challenge } from './challenge';


export interface Niveau { 
    id?: number;
    nom?: string;
    classes?: Array<Classe>;
    livres?: Array<Livre>;
    challenges?: Array<Challenge>;
}

