/**
 * API EDUGO - Plateforme Éducative Malienne
 *
 * Contact: support@edugo.ml
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ConversionEleve } from './conversionEleve';


export interface OptionsConversion { 
    id?: number;
    libelle?: string;
    etat?: boolean;
    nbrePoint?: number;
    dateAjout?: string;
    conversions?: Array<ConversionEleve>;
}

