/**
 * API EDUGO - Plateforme Éducative Malienne
 *
 * Contact: support@edugo.ml
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Eleve } from './eleve';
import { Badge } from './badge';
import { Challenge } from './challenge';


export interface Participation { 
    id?: number;
    score?: number;
    rang?: number;
    tempsPasse?: number;
    statut?: string;
    dateParticipation?: string;
    isaParticiper?: boolean;
    eleve?: Eleve;
    challenge?: Challenge;
    badge?: Badge;
}

