/**
 * API EDUGO - Plateforme Éducative Malienne
 *
 * Contact: support@edugo.ml
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ProgressionResponse { 
    id?: number;
    eleveId?: number;
    eleveNom?: string;
    livreId?: number;
    livreTitre?: string;
    pageActuelle?: number;
    pourcentageCompletion?: number;
    dateMiseAJour?: string;
}

