/**
 * API EDUGO - Plateforme Éducative Malienne
 *
 * Contact: support@edugo.ml
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Eleve } from './eleve';
import { Livre } from './livre';


export interface Progression { 
    id?: number;
    pourcentageCompletion?: number;
    tempsLecture?: number;
    pageActuelle?: number;
    dateDerniereLecture?: string;
    eleve?: Eleve;
    livre?: Livre;
    dateMiseAJour?: string;
}

