/**
 * API EDUGO - Plateforme Éducative Malienne
 *
 * Contact: support@edugo.ml
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TypeQuestion } from './typeQuestion';
import { Exercice } from './exercice';
import { Quiz } from './quiz';
import { ReponsePossible } from './reponsePossible';
import { ReponseEleve } from './reponseEleve';
import { Challenge } from './challenge';


export interface Question { 
    id?: number;
    enonce?: string;
    points?: number;
    dateCreation?: string;
    dateModification?: string;
    challenge?: Challenge;
    quiz?: Quiz;
    exercice?: Exercice;
    type?: TypeQuestion;
    reponsesPossibles?: Array<ReponsePossible>;
    reponsesEleves?: Array<ReponseEleve>;
}

