/**
 * API EDUGO - Plateforme Éducative Malienne
 *
 * Contact: support@edugo.ml
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface QuizResponse { 
    id?: number;
    titre?: string;
    description?: string;
    matiereId?: number;
    matiereNom?: string;
    niveauId?: number;
    niveauNom?: string;
    nombreQuestions?: number;
}

