/**
 * API EDUGO - Plateforme Éducative Malienne
 *
 * Contact: support@edugo.ml
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface Quiz { 
    id?: number;
    titre?: string;
    statut?: Quiz.StatutEnum;
    createdAt?: string;
    // Correspond au champ titreLivre (String) de QuizResponse côté backend
    titreLivre?: string;
    nombreQuestions?: number;
}
export namespace Quiz {
    export const StatutEnum = {
        Actif: 'ACTIF',
        Inactif: 'INACTIF',
        Brouillon: 'BROUILLON'
    } as const;
    export type StatutEnum = typeof StatutEnum[keyof typeof StatutEnum];
}


