/**
 * API EDUGO - Plateforme Éducative Malienne
 *
 * Contact: support@edugo.ml
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Question } from './question';
import { Livre } from './livre';


export interface Quiz { 
    id?: number;
    statut?: Quiz.StatutEnum;
    createdAt?: string;
    livre?: Livre;
    questionsQuiz?: Array<Question>;
    nombreQuestions?: number;
}
export namespace Quiz {
    export const StatutEnum = {
        Actif: 'ACTIF',
        Inactif: 'INACTIF',
        Brouillon: 'BROUILLON'
    } as const;
    export type StatutEnum = typeof StatutEnum[keyof typeof StatutEnum];
}


