/**
 * API EDUGO - Plateforme Éducative Malienne
 *
 * Contact: support@edugo.ml
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Demande de rafraîchissement du token JWT
 */
export interface RefreshTokenRequest { 
    /**
     * Token JWT de rafraîchissement
     */
    refreshToken: string;
}

