/**
 * API EDUGO - Plateforme Éducative Malienne
 *
 * Contact: support@edugo.ml
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Demande d\'inscription d\'un nouvel élève
 */
export interface RegisterRequest { 
    /**
     * Nom de famille
     */
    nom: string;
    /**
     * Prénom
     */
    prenom: string;
    /**
     * Email de l\'élève
     */
    email: string;
    /**
     * Mot de passe
     */
    motDePasse: string;
    /**
     * ID de la classe de l\'élève
     */
    classeId?: number;
    /**
     * Date de naissance
     */
    dateNaissance?: string;
}

