/**
 * API EDUGO - Plateforme Éducative Malienne
 *
 * Contact: support@edugo.ml
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Eleve } from './eleve';
import { Question } from './question';


export interface ReponseEleve { 
    id?: number;
    eleve?: Eleve;
    question?: Question;
    reponse?: string;
    pointsAttribues?: number;
    dateReponse?: string;
}

