/**
 * API EDUGO - Plateforme Éducative Malienne
 *
 * Contact: support@edugo.ml
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface RessourceIAResponse { 
    id?: number;
    titre?: string;
    type?: string;
    contenu?: string;
    fichierPath?: string;
    eleveId?: number;
    livreId?: number;
    matiereId?: number;
    createdAt?: string;
}

