/**
 * API EDUGO - Plateforme Éducative Malienne
 *
 * Contact: support@edugo.ml
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GrantedAuthority } from './grantedAuthority';


export interface User { 
    id?: number;
    nom?: string;
    prenom?: string;
    email?: string;
    motDePasse?: string;
    role?: User.RoleEnum;
    dateCreation?: string;
    dateModification?: string;
    estActive?: boolean;
    photoProfil?: string;
    enabled?: boolean;
    username?: string;
    password?: string;
    authorities?: Array<GrantedAuthority>;
    credentialsNonExpired?: boolean;
    accountNonExpired?: boolean;
    accountNonLocked?: boolean;
}
export namespace User {
    export const RoleEnum = {
        Admin: 'ADMIN',
        Eleve: 'ELEVE'
    } as const;
    export type RoleEnum = typeof RoleEnum[keyof typeof RoleEnum];
}


